### ISSUE TITLE
9.5 Compatibiliy broken

### ISSUE THREAD

**Issue by bebeGit** [maikschneider/bw_focuspoint_images#15]
https://github.com/maikschneider/bw_focuspoint_images/blob/dc9ec10aec0965a30b8750e2edc2e9683b0612de/Resources/Public/JavaScript/FocuspointWizard.js#L13

TYPO3/CMS/Backend/ActionButton/ImmediateAction only available  since 10.4 as i am aware

**Comment by maikschneider** [comment]
Hi @bebeGit, you're right, `ImmediateAction` is only available for v10+. However I didn't want to maintain an additional JS file, so I added a version check before using it, see [FocuspointWizard.js@v3.0.4](https://github.com/maikschneider/bw_focuspoint_images/blob/v3.0.4/Resources/Public/JavaScript/FocuspointWizard.js#L508). The error during import is not nice, but does not crash the rest of the application. 
Do you encounter great problems?

**Comment by maikschneider** [comment]
Hey @bebeGit, cool! Didn't think about putting the import into the condition. Have you installed the sources and could create a PR?

**Comment by maikschneider** [comment]
Fixed in [v3.0.5](https://github.com/maikschneider/bw_focuspoint_images/releases/tag/v3.0.5)
