### ISSUE TITLE
Focuspoint Processor: Access of non existing property target

### ISSUE THREAD

**Issue by 3l73** [maikschneider/bw_focuspoint_images#2]
Within the Focuspoint processor the property ‘target’ of standard object.

In some cases this property does not exists which leads to a warning within the TYPO3 log.

```
PHP Warning: Undefined property: stdClass::$target in public/typo3conf/ext/bw_focuspoint_images/Classes/DataProcessing/FocuspointProcessor.php line 57
```

Currently the code looks like this:

```php
if ($fieldValue->target) {
```

In order to reduce the log message, the existens of the property should be verified:

```php
if (property_exists($fieldValue, 'target') && $fieldValue->target) {
```

**Comment by maikschneider** [comment]
@3l73 Thanks for reporting this! I added your fix in [v3.0.4](https://github.com/maikschneider/bw_focuspoint_images/releases/tag/v3.0.4) :)
