### ISSUE TITLE
edit an exiting focuspoint

### ISSUE THREAD

**Issue by morange** [maikschneider/bw_focuspoint_images#26]
If a focus point has been created and you want to edit it later - this is not possible.
Is it possible to make the fields visible?

**Comment by maikschneider** [comment]
Cannot reproduce. You should be able to edit focus points by clicking the accordion tab in the sidebar or the focus box inside the image itself at any time.
You are using v12? Are there any JS errors in the console?

**Comment by morange** [comment]
After I was able to install the XIMA Manual Extension, the error no longer occurs.
I would say the ticket can be closed.
