### ISSUE TITLE
Wizard Template is not overridable

### ISSUE THREAD

**Issue by bebeGit** [maikschneider/bw_focuspoint_images#7]
https://github.com/maikschneider/bw_focuspoint_images/blob/94bea048504342aba02d26e7bd9df0e39ca0d008/Classes/Form/Wizard/FocusPointWizard.php#L87-L91C40

Suggest:
`$configurationManager = GeneralUtility::makeInstance(\TYPO3\CMS\Extbase\Configuration\ConfigurationManager::class);
        $pluginTS = $configurationManager->getConfiguration(ConfigurationManagerInterface::CONFIGURATION_TYPE_FULL_TYPOSCRIPT,'bw_focuspoint_images');
        $templateRootPaths = $pluginTS['plugin.']['tx_bwfocuspointimages.']['view.']['templateRootPaths.'];
        $partialRootPaths = $pluginTS['plugin.']['tx_bwfocuspointimages.']['view.']['partialRootPaths.'];        
        $templateView = GeneralUtility::makeInstance(StandaloneView::class);
        $templateView->setLayoutRootPaths(['EXT:bw_focuspoint_images/Resources/Private/Layouts']);
        $templateView->setPartialRootPaths($partialRootPaths);
        $templateView->setTemplateRootPaths($templateRootPaths);
        $templateView->setTemplate('FocuspointWizard');`

**Comment by maikschneider** [comment]
Yes, this looks good! Would you be so kind and open a PR?
