### ISSUE TITLE
Missing focus point settings

### ISSUE THREAD

**Issue by jackd248** [maikschneider/bw_focuspoint_images#9]
Hej,

thanks for porting the extension to TYPO3 v12!
Actually I got the problem, that I can't edit the focus point attributes within the editor. There are not input fields for name, description or color. Do you have an idea, why they are missing?

<img width="375" alt="Bildschirm­foto 2023-09-28 um 09 06 47" src="https://github.com/maikschneider/bw_focuspoint_images/assets/4558190/7e84c806-912a-4846-bfc6-61e9dddaaec8">

**Comment by maikschneider** [comment]
Hey, did you add any point settings?

> There are no default fields defined! An example with working frontend output can be found in the PageTS section.

**Comment by jackd248** [comment]
You're right, that's my fault. I was wondering, why no focus areas appearing in the frontend and thought this has to be done with the missing attributes, but this might be part of another problem.
